baseURL = "https://khancept032.github.io/Hugo-Web/"
languageCode = "en-us"
title = "Project-2"
theme = "hugo-theme-learn"
publishDir = "docs"


[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"
  disableNextPrev = true
